AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Task Definition'
Parameters:
  ProjectName:
    Type: String
    Default: ecs-practice

  EcsNameSuffix:
    Type: String
    Default: app

  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prd

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Mappings:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
  spec:
    dev:
      CPU: 1024
      Memory: 2GB

    prod:
      CPU: 1024
      Memory: 2GB

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Resources:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +

# - - - - - - - - - - - - - - - - -
  ECSTask:
# - - - - - - - - - - - - - - - - -
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        -
          Name: !Sub ${ProjectName}-httpd
          Image: httpd
          LogConfiguration:
            LogDriver: awsfirelens
          PortMappings:
            -
              HostPort: 80
              Protocol: tcp
              ContainerPort: 80
        - Name: !Sub ${ProjectName}-log-router
          Image: !Sub ${AWS::AccountId}.dkr.ecr.ap-northeast-1.amazonaws.com/ecs-practice/fluentbit-dev-my-firelens:latest
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub /ecs/${ProjectName}/fluentbit
              awslogs-region: "ap-northeast-1"
              awslogs-stream-prefix: "firelens"
          FirelensConfiguration:
            Type: fluentbit
            Options:
              config-file-type: file
              config-file-value: /fluent-bit/etc/extra.conf
          Environment:
            - Name: AWS_REGION
              Value: ap-northeast-1
            - Name: LOG_BUCKET_NAME
              Value: !Join [ '-', [ !Ref ProjectName, logs, !Ref Stage ] ]

      ExecutionRoleArn:
        Fn::ImportValue:
          !Sub ECS-ExecRoleArn-${ProjectName}
      TaskRoleArn:
        Fn::ImportValue:
          !Sub ECS-TaskRoleArn-${ProjectName}
      Family: !Sub '${ProjectName}-${EcsNameSuffix}'
      NetworkMode: awsvpc
      Cpu: !FindInMap [ spec, !Ref Stage, CPU ]
      Memory: !FindInMap [ spec, !Ref Stage, Memory ]
      RequiresCompatibilities:
        - FARGATE

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Outputs:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
# - - - - - - - - - - - - - - - - -
  ECSTask:
    Value: !Ref ECSTask
    Export:
      Name: !Join
            - '-'
            - - ECS
              - Task
              - !Ref ProjectName
              - !Ref EcsNameSuffix
