AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Bucket for ECS'
Parameters:
  ProjectName:
    Type: String
    Default: ecs-practice
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prd

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Resources:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
# - - - - - - - - - - - - - - - - -
  S3BucketResources:
# - - - - - - - - - - - - - - - - -
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${ProjectName}-logs-${Stage}-${AWS::AccountId}'
      AccessControl: Private
      VersioningConfiguration:
        Status: Suspended
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-logs-${Stage}-${AWS::AccountId}'
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Stage
          Value: !Ref Stage

  # - - - - - - - - - - - - - - - - -
  EcrRepositoryForFluentbit:
    # - - - - - - - - - - - - - - - - -
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Join
        - '/'
        - - !Ref ProjectName
          - 'fluentbit-dev-my-firelens'
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep all tagged images and untagged 5 images, expire all others",
                "action": {
                  "type": "expire"
                },
                "selection": {
                  "countType": "imageCountMoreThan",
                  "countNumber": 5,
                  "tagStatus": "untagged"
                }
              }
            ]
          }

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${ProjectName}/fluentbit'
      RetentionInDays: 365

Outputs:
  LogsBucketName:
    Description: ECS logs bucket name
    Value: !Ref S3BucketResources
    Export:
      Name: !Sub '${ProjectName}-${Stage}-logs-bucket-name'